name: Deploy to School Server

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/domeenid/www.ta19vikat.itmajakas.ee/oppematerjalid
            git fetch --tags
            git checkout ${{ github.ref_name }}
            npm ci
            npm run docs:build
